# FILE: launcher/main.py
# VERSION: 1.0.2
# START_MODULE_CONTRACT
#   PURPOSE: Provide the profile-aware launcher CLI for inspecting, planning, validating, and executing runtime contours.
#   SCOPE: CLI parsing and command dispatch for inspect, plan-run, doctor, bootstrap-env, check-env, exec, and create-env flows
#   DEPENDS: M-PROFILES
#   LINKS: M-LAUNCHER
#   ROLE: SCRIPT
#   MAP_MODE: LOCALS
# END_MODULE_CONTRACT
#
# START_MODULE_MAP
#   FAMILY_IMPORT_CHECKS - Runtime import probes keyed by supported profile family
#   _entrypoint_to_command - Translate a configured module entrypoint into an interpreter command
#   _build_compiled_requirements_preview - Build preview lines for the resolved dependency pack file
#   _compiled_requirements_payload - Serialize resolved dependency-pack metadata for operator-facing JSON output
#   _write_compiled_requirements_file - Materialize a temporary compiled requirements file for create-env execution
#   parse_args - Parse launcher CLI arguments and subcommands
#   main - Resolve the requested launcher command and emit JSON payloads or process exit codes
# END_MODULE_MAP
#
# START_CHANGE_SUMMARY
#   LAST_CHANGE: [v1.0.2 - Aligned launcher dependency contract with the package-level profiles import boundary without changing runtime behavior]
# END_CHANGE_SUMMARY

from __future__ import annotations

import argparse
import tempfile
import json
from pathlib import Path
import subprocess

from profiles import ProfileResolver


FAMILY_IMPORT_CHECKS = {
    "qwen": ("import importlib.util; import json; print(json.dumps({'torch': importlib.util.find_spec('torch') is not None, 'qwen_tts': importlib.util.find_spec('qwen_tts') is not None}))",),
    "piper": ("import importlib.util; import json; print(json.dumps({'onnxruntime': importlib.util.find_spec('onnxruntime') is not None, 'piper': importlib.util.find_spec('piper') is not None or importlib.util.find_spec('piper_tts') is not None}))",),
    "omnivoice": ("import importlib.util; import json; print(json.dumps({'torch': importlib.util.find_spec('torch') is not None, 'omnivoice': importlib.util.find_spec('omnivoice') is not None}))",),
}


# START_CONTRACT: _entrypoint_to_command
#   PURPOSE: Translate a configured module entrypoint into the exact command executed by the resolved interpreter.
#   INPUTS: { entrypoint: str - configured module entrypoint, python_path: str - resolved interpreter path }
#   OUTPUTS: { list[str] - subprocess-safe command sequence }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: _entrypoint_to_command
def _entrypoint_to_command(entrypoint: str, python_path: str) -> list[str]:
    prefix = "python -m "
    if entrypoint.startswith(prefix):
        return [python_path, "-m", entrypoint[len(prefix) :]]
    return [python_path, entrypoint]


# START_CONTRACT: _build_compiled_requirements_preview
#   PURPOSE: Build the human-readable preview used for compiled dependency pack output.
#   INPUTS: { resolved: object - resolved launch profile carrying family, module, host, and metadata fields }
#   OUTPUTS: { list[str] - preview file lines suitable for a requirements-style text file }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: _build_compiled_requirements_preview
def _build_compiled_requirements_preview(resolved: object) -> list[str]:
    pack_files = [Path(item) for item in resolved.metadata.get("pack_files", [])]
    lines = [
        "# generated by launcher",
        f"# family: {resolved.family.key}",
        f"# module: {resolved.module.key}",
        f"# platform: {resolved.host.platform_system.lower()}/{resolved.host.architecture.lower()}",
        "",
    ]
    lines.extend(f"-r {pack_file.resolve().as_posix()}" for pack_file in pack_files)
    return lines


# START_CONTRACT: _compiled_requirements_payload
#   PURPOSE: Serialize compiled dependency-pack metadata for launcher JSON responses.
#   INPUTS: { resolved: object - resolved launch profile carrying dependency metadata }
#   OUTPUTS: { dict[str, object] - JSON-serializable dependency plan payload }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: _compiled_requirements_payload
def _compiled_requirements_payload(resolved: object) -> dict[str, object]:
    return {
        "pack_refs": resolved.metadata.get("pack_refs", {}),
        "pack_files": list(resolved.metadata.get("pack_files", [])),
        "preview_lines": _build_compiled_requirements_preview(resolved),
    }


# START_CONTRACT: _write_compiled_requirements_file
#   PURPOSE: Materialize a temporary compiled requirements file for create-env execution.
#   INPUTS: { resolved: object - resolved launch profile carrying dependency metadata }
#   OUTPUTS: { str - temporary requirements file path }
#   SIDE_EFFECTS: Creates a temporary file on disk that callers are responsible for removing
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: _write_compiled_requirements_file
def _write_compiled_requirements_file(resolved: object) -> str:
    preview_lines = _build_compiled_requirements_preview(resolved)
    handle = tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        suffix="-requirements.txt",
        prefix=f"launcher-{resolved.family.key}-{resolved.module.key}-",
        delete=False,
    )
    try:
        handle.write("\n".join(preview_lines) + "\n")
    finally:
        handle.close()
    return handle.name


# START_CONTRACT: parse_args
#   PURPOSE: Parse launcher CLI arguments and select the requested profile-aware command.
#   INPUTS: none
#   OUTPUTS: { argparse.Namespace - parsed launcher command payload }
#   SIDE_EFFECTS: Reads process CLI arguments through argparse
#   LINKS: M-LAUNCHER
# END_CONTRACT: parse_args
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Profile-aware runtime launcher")
    parser.add_argument(
        "--project-root",
        help="override the repository root used to resolve profiles and isolated family environments",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    inspect_parser = subparsers.add_parser(
        "inspect",
        help="resolve a host+family+module launch profile and print it as JSON",
    )
    inspect_parser.add_argument("--family", required=True)
    inspect_parser.add_argument("--module", required=True)

    plan_run_parser = subparsers.add_parser(
        "plan-run",
        help="build an operator-facing launch plan for a resolved family+module profile",
    )
    plan_run_parser.add_argument("--family", required=True)
    plan_run_parser.add_argument("--module", required=True)

    doctor_parser = subparsers.add_parser(
        "doctor",
        help="inspect whether the expected isolated family environment and runtime pack are present",
    )
    doctor_parser.add_argument("--family", required=True)
    doctor_parser.add_argument("--module", required=True)

    bootstrap_parser = subparsers.add_parser(
        "bootstrap-env",
        help="print the exact environment bootstrap commands for a resolved family contour",
    )
    bootstrap_parser.add_argument("--family", required=True)
    bootstrap_parser.add_argument("--module", required=True)

    check_env_parser = subparsers.add_parser(
        "check-env",
        help="verify an existing isolated family environment and basic runtime imports",
    )
    check_env_parser.add_argument("--family", required=True)
    check_env_parser.add_argument("--module", required=True)

    exec_parser = subparsers.add_parser(
        "exec",
        help="execute a module entrypoint through the resolved family interpreter, or print the command in dry-run mode",
    )
    exec_parser.add_argument("--family", required=True)
    exec_parser.add_argument("--module", required=True)
    exec_parser.add_argument("--dry-run", action="store_true")

    create_env_parser = subparsers.add_parser(
        "create-env",
        help="create the resolved isolated family environment and install its runtime pack when --apply is passed",
    )
    create_env_parser.add_argument("--family", required=True)
    create_env_parser.add_argument("--module", required=True)
    create_env_parser.add_argument("--apply", action="store_true")
    return parser.parse_args()


# START_CONTRACT: main
#   PURPOSE: Execute the requested launcher command against a resolved family and module profile.
#   INPUTS: none
#   OUTPUTS: { int - process exit code for the selected launcher flow }
#   SIDE_EFFECTS: Resolves host and runtime profiles, prints JSON payloads, and may spawn subprocesses for env or entrypoint execution
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: main
def main() -> int:
    # START_BLOCK_RESOLVE_COMMAND_CONTEXT
    args = parse_args()
    resolver = (
        ProfileResolver(Path(args.project_root).resolve())
        if args.project_root
        else ProfileResolver()
    )
    # END_BLOCK_RESOLVE_COMMAND_CONTEXT

    # START_BLOCK_DISPATCH_COMMAND
    if args.command == "inspect":
        payload = resolver.resolve(family=args.family, module=args.module).to_dict()
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0
    if args.command == "plan-run":
        resolved = resolver.resolve(family=args.family, module=args.module)
        payload = resolved.to_dict()
        payload["launch_plan"] = {
            "family": resolved.family.key,
            "module": resolved.module.key,
            "required_env_name": resolved.required_env_name,
            "expected_python_path": resolved.expected_python_path,
            "dependency_plan": _compiled_requirements_payload(resolved),
            "entrypoint": resolved.module.entrypoint,
            "selected_backend": resolved.selected_backend,
            "backend_candidates": list(resolved.backend_candidates),
            "compatible": resolved.compatible,
            "reasons": list(resolved.reasons),
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0
    if args.command == "doctor":
        resolved = resolver.resolve(family=args.family, module=args.module)
        pack_files = [Path(item) for item in resolved.metadata.get("pack_files", [])]
        expected_python = Path(resolved.expected_python_path or "")
        env_root = expected_python.parent.parent if expected_python.name.lower() == "python.exe" else expected_python.parent.parent
        checks = {
            "pack_files_exist": all(pack_file.exists() for pack_file in pack_files),
            "expected_env_root_exists": env_root.exists(),
            "expected_python_exists": expected_python.exists(),
        }
        missing_steps = []
        missing_pack_files = [str(pack_file) for pack_file in pack_files if not pack_file.exists()]
        if missing_pack_files:
            missing_steps.append("dependency_pack_missing_from_repo")
        if not checks["expected_env_root_exists"]:
            missing_steps.append(f"create_env:{env_root}")
        if checks["expected_env_root_exists"] and not checks["expected_python_exists"]:
            missing_steps.append(f"python_missing_in_env:{expected_python}")
        payload = resolved.to_dict()
        payload["doctor"] = {
            "family": resolved.family.key,
            "module": resolved.module.key,
            "pack_files": [str(pack_file) for pack_file in pack_files],
            "missing_pack_files": missing_pack_files,
            "compiled_requirements": _compiled_requirements_payload(resolved),
            "expected_env_root": str(env_root),
            "expected_python_path": str(expected_python),
            "checks": checks,
            "missing_steps": missing_steps,
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0
    if args.command == "bootstrap-env":
        resolved = resolver.resolve(family=args.family, module=args.module)
        env_root = Path(resolved.expected_python_path).parent.parent
        bootstrap = {
            "family": resolved.family.key,
            "module": resolved.module.key,
            "expected_env_root": str(env_root),
            "expected_python_path": resolved.expected_python_path,
            "compiled_requirements": _compiled_requirements_payload(resolved),
            "backend_candidates": list(resolved.backend_candidates),
            "suggested_backend_env": resolved.selected_backend,
            "commands": {
                "create_env": f"py -3.11 -m venv {env_root}",
                "set_backend": f"set QWEN_TTS_BACKEND={resolved.selected_backend}" if resolved.selected_backend else None,
                "upgrade_pip": f"{resolved.expected_python_path} -m pip install --upgrade pip",
                "install_compiled_requirements": f"{resolved.expected_python_path} -m pip install -r <temp compiled requirements file>",
            },
        }
        payload = resolved.to_dict()
        payload["bootstrap_env"] = bootstrap
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0
    if args.command == "check-env":
        resolved = resolver.resolve(family=args.family, module=args.module)
        expected_python = Path(resolved.expected_python_path or "")
        env_exists = expected_python.parent.parent.exists()
        python_exists = expected_python.exists()
        import_check = None
        if python_exists:
            command = [str(expected_python), "-c", *FAMILY_IMPORT_CHECKS[resolved.family.key]]
            completed = subprocess.run(command, capture_output=True, text=True, check=False)
            parsed = None
            if completed.stdout:
                try:
                    parsed = json.loads(completed.stdout.strip())
                except Exception:
                    parsed = {"raw_stdout": completed.stdout.strip()}
            import_check = {
                "returncode": completed.returncode,
                "stdout": parsed,
                "stderr": completed.stderr.strip(),
            }
        payload = resolved.to_dict()
        payload["check_env"] = {
            "family": resolved.family.key,
            "module": resolved.module.key,
            "expected_python_path": str(expected_python),
            "checks": {
                "expected_env_root_exists": env_exists,
                "expected_python_exists": python_exists,
            },
            "compiled_requirements": _compiled_requirements_payload(resolved),
            "import_check": import_check,
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0
    if args.command == "exec":
        resolved = resolver.resolve(family=args.family, module=args.module)
        expected_python = Path(resolved.expected_python_path or "")
        command = _entrypoint_to_command(resolved.module.entrypoint, str(expected_python))
        payload = resolved.to_dict()
        payload["exec"] = {
            "family": resolved.family.key,
            "module": resolved.module.key,
            "command": command,
            "dry_run": bool(args.dry_run),
            "python_exists": expected_python.exists(),
        }
        if args.dry_run:
            print(json.dumps(payload, ensure_ascii=False, indent=2))
            return 0
        if not expected_python.exists():
            payload["exec"]["error"] = "expected_python_missing"
            print(json.dumps(payload, ensure_ascii=False, indent=2))
            return 1
        completed = subprocess.run(command, check=False)
        return completed.returncode
    if args.command == "create-env":
        resolved = resolver.resolve(family=args.family, module=args.module)
        expected_python = Path(resolved.expected_python_path or "")
        env_root = expected_python.parent.parent
        payload = resolved.to_dict()
        compiled_requirements_path = _write_compiled_requirements_file(resolved)
        payload["create_env"] = {
            "family": resolved.family.key,
            "module": resolved.module.key,
            "apply": bool(args.apply),
            "expected_env_root": str(env_root),
            "expected_python_path": str(expected_python),
            "compiled_requirements_path": compiled_requirements_path,
            "compiled_requirements": _compiled_requirements_payload(resolved),
            "steps": [
                ["py", "-3.11", "-m", "venv", str(env_root)],
                [str(expected_python), "-m", "pip", "install", "--upgrade", "pip"],
                [str(expected_python), "-m", "pip", "install", "-r", compiled_requirements_path],
            ],
            "env_already_exists": expected_python.exists(),
        }
        if not args.apply:
            print(json.dumps(payload, ensure_ascii=False, indent=2))
            return 0
        create_env_command, upgrade_pip_command, install_compiled_requirements_command = payload["create_env"]["steps"]
        try:
            if not expected_python.exists():
                subprocess.run(create_env_command, check=True)
            subprocess.run(upgrade_pip_command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(
                install_compiled_requirements_command,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
        except subprocess.CalledProcessError as exc:
            payload["create_env"]["created"] = expected_python.exists()
            payload["create_env"]["error"] = {
                "step": (
                    "install_compiled_requirements"
                    if exc.cmd == install_compiled_requirements_command
                    else "upgrade_pip"
                    if exc.cmd == upgrade_pip_command
                    else "bootstrap"
                ),
                "command": exc.cmd,
                "returncode": exc.returncode,
                "stdout": (exc.stdout or "").strip(),
                "stderr": (exc.stderr or "").strip(),
            }
            print(json.dumps(payload, ensure_ascii=False, indent=2))
            Path(compiled_requirements_path).unlink(missing_ok=True)
            return 1
        payload["create_env"]["created"] = expected_python.exists()
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        Path(compiled_requirements_path).unlink(missing_ok=True)
        return 0
    # END_BLOCK_DISPATCH_COMMAND
    raise ValueError(f"Unsupported launcher command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
